export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';

export const FETCH_BURGER_INITIAL_REQUEST = 'FETCH_BURGER_INITIAL_REQUEST';
export const FETCH_BURGER_INITIAL_SUCCESS = 'FETCH_BURGER_INITIAL_SUCCESS';
export const FETCH_BURGER_INITIAL_FAILURE = 'FETCH_BURGER_INITIAL_FAILURE';

export const FETCH_PURCHASE_REQUEST = 'FETCH_PURCHASE_REQUEST';
export const FETCH_PURCHASE_SUCCESS = 'FETCH_PURCHASE_SUCCESS';
export const FETCH_PURCHASE_FAILURE = 'FETCH_PURCHASE_FAILURE';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';

export const FETCH_AUTH_REQUEST = 'FETCH_AUTH_REQUEST';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_FAILURE = 'FETCH_AUTH_FAILURE';
export const FETCH_AUTH_LOGOUT = 'FETCH_AUTH_LOGOUT';
export const FETCH_AUTH_REDIRECT_PATH = 'FETCH_AUTH_REDIRECT_PATH';